[selenium]
driver               = "chrome"
headless             = true
headless_window_size = "1920x1080"
logging              = false
log_file             = "selenium.log"
pause_at_end         = false

[ghes]
url = "http://example.com"
password = "CHANGEME"
username = "ghe-admin"
pat = "CHANGEME"

[classic-pat]
# Use ">>>RANDOM<<<" in the "note" field, to have a randomly generated note
note = ">>>RANDOM<<<"

# Note: Double quotes are used around the keys, because tomllib doesn't like
#       colons in key names unless the key names are double quoted

[classic-pat.scopes]
"repo"                      = true
"repo:status"               = true
"repo_deployment"           = true
"public_repo"               = true
"repo:invite"               = true
"security_events"           = true
"workflow"                  = true
"write:packages"            = true
"read:packages"             = true
"delete:packages"           = true
"admin:org"                 = true
"write:org"                 = true
"read:org"                  = true
"manage_runners:org"        = true
"admin:public_key"          = true
"write:public_key"          = true
"read:public_key"           = true
"admin:repo_hook"           = true
"write:repo_hook"           = true
"read:repo_hook"            = true
"admin:org_hook"            = true
"gist"                      = true
"notifications"             = true
"user"                      = true
"read:user"                 = true
"user:email"                = true
"user:follow"               = true
"delete_repo"               = true
"write:discussion"          = true
"read:discussion"           = true
"admin:enterprise"          = true
"manage_runners:enterprise" = true
"manage_billing:enterprise" = true
"read:enterprise"           = true
"admin:pre_receive_hook"    = true
"site_admin"                = true
"admin:gpg_key"             = true
"admin:ssh_signing_key"     = true

[org]
name = "CHANGEME"
members = ["ghe-admin"]